### ISSUE TITLE
Apply Byzantium changes

### ISSUE THREAD

**Issue by pirapira** [pirapira/eth-isabelle#459]
* [ ] <del>[EIP 5/8](https://github.com/ethereum/EIPs/issues/8)</del> https://github.com/ethereum/EIPs/pull/211 (RETURNDATACOPY and RETURNDATASIZE) 
* [ ] [EIP 96](https://github.com/ethereum/EIPs/pull/210) (block hash in a special contract) | https://github.com/ethereum/yellowpaper/pull/311
* [ ] [EIP 98](https://github.com/ethereum/EIPs/pull/658) remove medstate from transaction receipts | already in `metropolis` branch
* [ ] [EIP 100](https://github.com/ethereum/EIPs/issues/100) (difficulty adjustment) (equation (43).  2017-02-17: two options still; 2017-03-02 perhaps option 1(b))
* [ ] <del>[EIP 101](https://github.com/ethereum/EIPs/issues/101)</del> [EIP 198](https://github.com/ethereum/EIPs/pull/198) (Big-int precompiles)
* [ ] <del>[EIP 116](https://github.com/ethereum/EIPs/issues/116)</del> https://github.com/ethereum/EIPs/pull/214 (STATIC_CALL)
* [ ] EIP <del>[196](https://github.com/ethereum/EIPs/issues/196)</del> https://github.com/ethereum/EIPs/pull/213 & <del>[197](https://github.com/ethereum/EIPs/issues/197) </del> https://github.com/ethereum/EIPs/pull/212 (zkSNARK verification primitives)
* [ ] EIP [206](https://github.com/ethereum/EIPs/pull/206) (REVERT) to be followed
* [ ] EIP [649](https://github.com/ethereum/EIPs/pull/669)
* [ ] EIP [658](https://github.com/ethereum/EIPs/pull/658/files) (add status code in receipts)

The list was copied from https://github.com/ethereum/yellowpaper/issues/229 and adjusted.
